# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/siim-covid-19',
                'doc_host': 'https://sdhca.github.io',
                'git_url': 'https://github.com/sdhca/siim-covid-19',
                'lib_path': 'siim_covid_19'},
  'syms': {'siim_covid_19.core': {'siim_covid_19.core.foo': ('core.html#foo', 'siim_covid_19/core.py')}}}